{% set version = "1.0.1" %}

package:
    name: ffbidx
    version: {{ version }}

source:
    git_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer.git  # [linux_64]
    #git_rev: {{ "v"+version }}
    # for conda-forge use url instead:
    #url: https://github.com/paulscherrerinstitute/fast-feedback-indexer/archive/refs/tags/v{{ version }}.tar.gz
    #sha256: a01ee8f31eab998391aa159e1c8eb506ea4e79b44d2d9a576bc692f73e977625

build:
    number: 0
    skip: True  # [not linux64]

requirements:
    build:
        - {{ compiler('cxx') }}
        # for conda-forge add this
        #- {{ stdlib('c') }}
        #- conda-forge::eigen
        - conda-forge::meson
        - conda-forge::cuda-compiler >=10.0.0
        - conda-forge::numpy
        - conda-forge::python >=3.5
    run:
        - {{ pin_compatible('numpy') }}
        - conda-forge::cuda-cudart >=10.0.0

test:
    imports:
        - ffbidx

about:
    home: https://github.com/paulscherrerinstitute/fast-feedback-indexer
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.md
    license_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer/LICENSE.md
    summary: "Fast feedback indexer library with python module for xray crystallography"
    description: |
        Fast feedback indexer library with the python module for xray crystallography.
        Paper reference: https://doi.org/10.1107/S1600576724003182
        Code repository: https://github.com/paulscherrerinstitute/fast-feedback-indexer
    dev_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer
    doc_url: https://github.com/paulscherrerinstitute/fast-feedback-indexer/blob/main/python/README.md

extra:
  recipe-maintainers:
        - hcstadler
